/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.clyze.antlr2datalog;

import org.junit.Test;
import static org.junit.Assert.*;

public class MainTest {
    @Test public void testAppHasAGreeting() {
        Main classUnderTest = new Main();
        assertNotNull(null);
    }
}
